version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db:/var/lib/postgresql/data

  odoo-init:
    image: odoo:18.0
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: odoo
    command: ["odoo", "-i", "base", "--database=odoo", "--without-demo=all", "--stop-after-init"]
    volumes:
      - odoo-web:/var/lib/odoo

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: odoo
    volumes:
      - odoo-web:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    restart: always
    # Wird erst nach Initialisierung manuell gestartet

volumes:
  odoo-db:
  odoo-web:
